README update (link to repos)
CMD: jtscm-autosync self

# On branch main
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	modified:   README.md
#	modified:   ku/install
#	modified:   ku/klabs_makeport
#

diff --git a/ku/klabs_makeport b/ku/klabs_makeport
--- a/ku/klabs_makeport
+++ b/ku/klabs_makeport
@@ -2,6 +2,12 @@
 
 set -e -u
 
+which jtcj >/dev/null || {
+	echo -e "\n$0 error: 'jtcj' command missing" >&2
+	echo "	you need to install ku-jtools package\n" >&2
+	exit 1
+}
+
 parms=
 
 [ $# = 0 ] && {
